/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as HorizonRouteImport } from './routes/horizon'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as ProjectIntelligenceRouteImport } from './routes/project-intelligence'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const HorizonRoute = HorizonRouteImport.update({
  id: '/horizon',
  path: '/horizon',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIntelligenceRoute = ProjectIntelligenceRouteImport.update({
  id: '/project-intelligence',
  path: '/project-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agb': typeof AgbRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/horizon': typeof HorizonRoute
  '/impressum': typeof ImpressumRoute
  '/project-intelligence': typeof ProjectIntelligenceRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agb': typeof AgbRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/horizon': typeof HorizonRoute
  '/impressum': typeof ImpressumRoute
  '/project-intelligence': typeof ProjectIntelligenceRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agb': typeof AgbRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/horizon': typeof HorizonRoute
  '/impressum': typeof ImpressumRoute
  '/project-intelligence': typeof ProjectIntelligenceRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agb'
    | '/contact'
    | '/datenschutz'
    | '/horizon'
    | '/impressum'
    | '/project-intelligence'
    | '/projects'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agb'
    | '/contact'
    | '/datenschutz'
    | '/horizon'
    | '/impressum'
    | '/project-intelligence'
    | '/projects'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agb'
    | '/contact'
    | '/datenschutz'
    | '/horizon'
    | '/impressum'
    | '/project-intelligence'
    | '/projects'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgbRoute: typeof AgbRoute
  ContactRoute: typeof ContactRoute
  DatenschutzRoute: typeof DatenschutzRoute
  HorizonRoute: typeof HorizonRoute
  ImpressumRoute: typeof ImpressumRoute
  ProjectIntelligenceRoute: typeof ProjectIntelligenceRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horizon': {
      id: '/horizon'
      path: '/horizon'
      fullPath: '/horizon'
      preLoaderRoute: typeof HorizonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-intelligence': {
      id: '/project-intelligence'
      path: '/project-intelligence'
      fullPath: '/project-intelligence'
      preLoaderRoute: typeof ProjectIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgbRoute: AgbRoute,
  ContactRoute: ContactRoute,
  DatenschutzRoute: DatenschutzRoute,
  HorizonRoute: HorizonRoute,
  ImpressumRoute: ImpressumRoute,
  ProjectIntelligenceRoute: ProjectIntelligenceRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
